# -*- coding: utf-8 -*-
"""ChatbotBalmon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pg3rp20IKyIqAgd6EysA9hb9ATv2RGZ9
"""

# @title Langkah 1: Install Semua Library 🛠️
# Install Browser untuk Scraping
!apt-get update > /dev/null
!apt-get install firefox -y > /dev/null
!wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
!tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
!chmod +x geckodriver
!mv geckodriver /usr/local/bin/

# Install Library Python (AI & Database)
!pip install selenium webdriver-manager > /dev/null
!pip install langchain langchain-community langchain-chroma sentence-transformers > /dev/null
!pip install openai > /dev/null  # DeepSeek pakai format OpenAI

print("✅ Tahap 1 Selesai: Semua alat sudah terpasang!")

# @title 1. Install Library Khusus (PDF & OCR Gambar) 🛠️
# Install mesin pembaca gambar (Tesseract) di Linux Colab
!sudo apt install tesseract-ocr -y > /dev/null
!sudo apt install libtesseract-dev -y > /dev/null

# Install library Python penghubungnya
!pip install pytesseract pdf2image pypdf pillow langchain-community > /dev/null

print("✅ Alat baca PDF dan Gambar berhasil diinstal!")

# @title 2. Proses SEMUA Data (PDF + Word + Gambar + Teks) - REVISI ✅
import os
import glob
# Menggunakan langchain_community sesuai versi terbaru
from langchain_community.document_loaders import PyPDFLoader, TextLoader, Docx2txtLoader
# PERBAIKAN: Mengambil Document dari 'langchain_core' bukan 'langchain.docstore'
from langchain_core.documents import Document
from PIL import Image
import pytesseract

# Konfigurasi Folder
FOLDER_PATH = "Data_balmon"
all_documents = []

print(f"🚀 Memulai pemrosesan data LENGKAP di folder '{FOLDER_PATH}'...")

if not os.path.exists(FOLDER_PATH):
    print(f"⚠️ Folder '{FOLDER_PATH}' tidak ditemukan. Buat folder dan upload file dulu!")
else:
    # -----------------------------------------
    # A. PROSES FILE WORD (.DOCX)
    # -----------------------------------------
    word_files = glob.glob(f"{FOLDER_PATH}/*.docx")
    for file in word_files:
        try:
            loader = Docx2txtLoader(file)
            data = loader.load()
            all_documents.extend(data)
            print(f"   ✅ Word (.docx) Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca Word {os.path.basename(file)}: {e}")

    # -----------------------------------------
    # B. PROSES PDF
    # -----------------------------------------
    pdf_files = glob.glob(f"{FOLDER_PATH}/*.pdf")
    for file in pdf_files:
        try:
            loader = PyPDFLoader(file)
            data = loader.load()
            all_documents.extend(data)
            print(f"   ✅ PDF Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca PDF {os.path.basename(file)}: {e}")

    # -----------------------------------------
    # C. PROSES GAMBAR (OCR)
    # -----------------------------------------
    img_files = glob.glob(f"{FOLDER_PATH}/*.jpg") + glob.glob(f"{FOLDER_PATH}/*.png") + glob.glob(f"{FOLDER_PATH}/*.jpeg")
    for file in img_files:
        try:
            text_result = pytesseract.image_to_string(Image.open(file))
            if len(text_result.strip()) > 10:
                # Bungkus jadi format Document
                doc = Document(page_content=text_result, metadata={"source": file})
                all_documents.append(doc)
                print(f"   ✅ Gambar (OCR) Terbaca: {os.path.basename(file)}")
            else:
                print(f"   ⚠️ Gambar {os.path.basename(file)} buram/kosong.")
        except Exception as e:
            print(f"   ❌ Gagal baca Gambar {os.path.basename(file)}: {e}")

    # -----------------------------------------
    # D. PROSES FILE TEKS (.TXT)
    # -----------------------------------------
    txt_files = glob.glob(f"{FOLDER_PATH}/*.txt")
    for file in txt_files:
        try:
            loader = TextLoader(file)
            data = loader.load()
            all_documents.extend(data)
            print(f"   ✅ Teks Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca Teks {os.path.basename(file)}: {e}")

    print("="*40)
    print(f"🎉 TOTAL DOKUMEN: {len(all_documents)} file berhasil diproses!")
    print("   (Silakan lanjutkan ke Tahap 3: Update Database)")

# @title 🛠️ FIX TOTAL: Install & Proses Ulang (Anti-Gagal)
# 1. Install library yang kurang & yang lebih kuat (PyMuPDF)
print("⏳ Menginstal library tambahan (docx2txt & pymupdf)...")
!pip install docx2txt pymupdf > /dev/null

import os
import glob
# Kita ganti PyPDFLoader dengan PyMuPDFLoader yang lebih 'sakti'
from langchain_community.document_loaders import PyMuPDFLoader, TextLoader, Docx2txtLoader
from langchain_core.documents import Document
from PIL import Image
import pytesseract

# Konfigurasi Folder
FOLDER_PATH = "data_balmon" # Sesuaikan jika nama folder Anda beda (misal "Data_balmon")
# Di log Anda folder bernama 'Data_balmon' (huruf besar D), mari kita cek keduanya
if not os.path.exists(FOLDER_PATH) and os.path.exists("Data_balmon"):
    FOLDER_PATH = "Data_balmon"

all_documents = []

print(f"🚀 Memulai pemrosesan ulang di folder '{FOLDER_PATH}'...")

if not os.path.exists(FOLDER_PATH):
    print(f"⚠️ Folder '{FOLDER_PATH}' tidak ditemukan.")
else:
    # -----------------------------------------
    # A. PROSES FILE WORD (.DOCX) - (Perbaikan: Library sudah diinstall)
    # -----------------------------------------
    word_files = glob.glob(f"{FOLDER_PATH}/*.docx")
    for file in word_files:
        try:
            loader = Docx2txtLoader(file)
            data = loader.load()
            all_documents.extend(data)
            print(f"   ✅ Word Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca Word {os.path.basename(file)}: {e}")

    # -----------------------------------------
    # B. PROSES PDF (Perbaikan: Pakai PyMuPDF)
    # -----------------------------------------
    pdf_files = glob.glob(f"{FOLDER_PATH}/*.pdf")
    for file in pdf_files:
        try:
            # Menggunakan PyMuPDFLoader yang lebih tahan banting terhadap error 'bbox'
            loader = PyMuPDFLoader(file)
            data = loader.load()
            all_documents.extend(data)
            print(f"   ✅ PDF Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca PDF {os.path.basename(file)}: {e}")

    # -----------------------------------------
    # C. PROSES GAMBAR (OCR)
    # -----------------------------------------
    img_files = glob.glob(f"{FOLDER_PATH}/*.jpg") + glob.glob(f"{FOLDER_PATH}/*.png") + glob.glob(f"{FOLDER_PATH}/*.jpeg")
    for file in img_files:
        try:
            text_result = pytesseract.image_to_string(Image.open(file))
            if len(text_result.strip()) > 10:
                doc = Document(page_content=text_result, metadata={"source": file})
                all_documents.append(doc)
                print(f"   ✅ Gambar (OCR) Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca Gambar {os.path.basename(file)}: {e}")

    # -----------------------------------------
    # D. PROSES FILE TEKS
    # -----------------------------------------
    txt_files = glob.glob(f"{FOLDER_PATH}/*.txt")
    for file in txt_files:
        try:
            loader = TextLoader(file)
            data = loader.load()
            all_documents.extend(data)
            print(f"   ✅ Teks Terbaca: {os.path.basename(file)}")
        except Exception as e:
            print(f"   ❌ Gagal baca Teks {os.path.basename(file)}: {e}")

    print("="*40)
    print(f"🎉 TOTAL DOKUMEN BERHASIL: {len(all_documents)}")
    print("   (Data siap! Lanjutkan ke Tahap 3: Update Database)")

# @title 3. Update Database Pengetahuan (ChromaDB) - FIX V2 🧠

# 1. Install Library khusus pemecah teks (Solusi Error ModuleNotFoundError)
print("⏳ Menginstal library text-splitters...")
!pip install langchain-text-splitters > /dev/null

# 2. Import Library (Perhatikan baris import pertama yang baru)
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# 3. Cek apakah data dokumen ada di memori
if 'all_documents' not in locals() or len(all_documents) == 0:
    print("❌ TIDAK ADA DATA! Mohon jalankan kode 'TAHAP 2 (FIX TOTAL)' terlebih dahulu.")
else:
    print(f"⏳ Sedang memproses {len(all_documents)} dokumen...")

    # 4. Pecah teks menjadi potongan kecil (Chunking)
    # chunk_size=800 artinya setiap potongan berisi sekitar 800 karakter
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)
    chunks = text_splitter.split_documents(all_documents)

    print(f"   ↳ Data dipecah menjadi {len(chunks)} potongan informasi.")

    # 5. Download Model Penerjemah Bahasa ke Angka (Embedding)
    print("⏳ Sedang mengubah teks menjadi vektor (Embedding)...")
    embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

    # 6. Simpan ke Database Chroma
    # Menghapus database lama agar bersih (reset)
    !rm -rf ./chroma_db

    db = Chroma.from_documents(chunks, embedding_model, persist_directory="./chroma_db")

    print("\n" + "="*40)
    print(f"✅ DATABASE SIAP! Otak AI sudah berisi {len(chunks)} informasi.")
    print("   (Lanjut ke Tahap 4: Jalankan Chatbot)")
    print("="*40)

# @title 4. Mulai Chatbot Balmon (DeepSeek) 🤖
from openai import OpenAI

# ==========================================
# 🔑 KONFIGURASI API KEY
# ==========================================
# Ganti tulisan di bawah ini dengan API Key DeepSeek Anda
# Jika belum punya, daftar di: https://platform.deepseek.com (Gratis)
MY_API_KEY = "sk-27e056758cc64986aaeda21e5d930794"  # <--- TEMPEL API KEY DI SINI (Jangan hapus tanda kutipnya)
BASE_URL = "https://api.deepseek.com"

# Inisialisasi Client
try:
    client = OpenAI(api_key=MY_API_KEY, base_url=BASE_URL)
except Exception as e:
    print(f"❌ Error Setup: {e}")

def cari_jawaban(pertanyaan):
    """Mencari data relevan di database Chroma"""
    # Mencari 4 potongan teks paling mirip dengan pertanyaan
    # k=4 artinya kita ambil 4 referensi teratas
    docs = db.similarity_search(pertanyaan, k=4)

    # Gabungkan teksnya jadi satu paragraf panjang
    context = "\n\n".join([d.page_content for d in docs])
    return context

print("\n🤖 CHATBOT BALMON ONLINE!")
print("   (Ketik 'keluar' atau 'exit' untuk berhenti)")
print("-" * 50)

# History Chat (Agar bot ingat percakapan sebelumnya)
chat_history = [
    {"role": "system", "content": "Kamu adalah Asisten AI Profesional untuk Kantor Balai Monitor (Balmon). Jawablah pertanyaan user HANYA berdasarkan KNOWLEDGE BASE (Referensi Dokumen) yang diberikan. Jika info tidak ada di dokumen, katakan 'Maaf, informasi tersebut tidak tersedia di dokumen saya'. Jangan mengarang."}
]

while True:
    # Input dari User
    user_input = input("\nAnda: ")

    # Cek kata kunci keluar
    if user_input.lower() in ["keluar", "exit", "stop", "sudah"]:
        print("Bot: Sampai jumpa! Semangat magangnya! 👋")
        break

    # 1. Cari Konteks di Dokumen Anda (RAG)
    try:
        print("   (Mencari di dokumen...)", end="\r") # Indikator loading
        konteks_data = cari_jawaban(user_input)
    except Exception as e:
        print("⚠️ Error Database: Pastikan Tahap 3 sudah dijalankan dengan sukses.")
        continue

    # 2. Masukkan Konteks ke Prompt
    pesan_untuk_ai = f"""
    PERTANYAAN USER: {user_input}

    REFERENSI DOKUMEN (KNOWLEDGE BASE):
    {konteks_data}

    Tolong jawab pertanyaan user menggunakan Referensi Dokumen di atas.
    Jika ada langkah-langkah, jelaskan dengan poin-poin agar rapi.
    """

    # Tambahkan ke history sementara
    chat_history.append({"role": "user", "content": pesan_untuk_ai})

    # 3. Kirim ke DeepSeek
    try:
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=chat_history,
            stream=False
        )

        jawaban = response.choices[0].message.content
        print(f"Bot: {jawaban}")

        # Simpan jawaban bot ke history (agar nyambung jika ditanya lagi)
        chat_history.append({"role": "assistant", "content": jawaban})

        # Bersihkan prompt user agar history tidak kepenuhan dengan konteks dokumen
        chat_history[-2] = {"role": "user", "content": user_input}

    except Exception as e:
        print(f"\n❌ Error API: {e}")
        print("   TIPS: Cek apakah API Key sudah benar? Atau saldo trial habis?")

# @title 4. Mulai Chatbot Balmon (Versi FINAL - Gemini 1.5 Flash) 🚀
# 1. Install Library Google AI
!pip install -q -U google-generativeai

import google.generativeai as genai
import sys

# ==========================================
# 🔑 TEMPEL API KEY ANDA DI BAWAH INI
# ==========================================
# Saya sudah masukkan API Key yang Anda kirimkan tadi:
GOOGLE_API_KEY = "AIzaSyCw6qFvcxl3wLwIHLE9isbhBULl7h9GGZg"

try:
    # Setup Google Gemini
    genai.configure(api_key=GOOGLE_API_KEY)

    # Menggunakan model 'gemini-1.5-flash' (Cepat & Gratis)
    model = genai.GenerativeModel('gemini-1.5-flash')

    print("✅ Koneksi ke Google Gemini BERHASIL!")

except Exception as e:
    print(f"❌ Gagal Setting API: {e}")
    sys.exit()

def cari_jawaban(pertanyaan):
    """Mencari data relevan di database Chroma"""
    try:
        # Mencari 4 potongan teks paling mirip
        docs = db.similarity_search(pertanyaan, k=4)
        # Gabungkan teksnya
        context = "\n\n".join([d.page_content for d in docs])
        return context
    except NameError:
        return "DATABASE BELUM DILOAD (Mohon jalankan Tahap 3 dulu)"

print("\n🤖 CHATBOT BALMON SIAP MELAYANI!")
print("   (Ketik 'keluar' untuk berhenti)")
print("-" * 50)

# History Chat
chat_history = []

while True:
    user_input = input("\nAnda: ")

    if user_input.lower() in ["keluar", "exit", "stop", "sudah"]:
        print("Bot: Sampai jumpa! Semoga laporannya lancar! 👋")
        break

    # 1. Cari Konteks di Dokumen (RAG)
    try:
        print("   (Mencari di dokumen...)", end="\r")
        konteks_data = cari_jawaban(user_input)
    except Exception as e:
        print("⚠️ Database belum siap. Pastikan Tahap 3 sukses.")
        continue

    # 2. Susun Prompt
    prompt_final = f"""
    Kamu adalah Asisten AI untuk Kantor Balai Monitor (Balmon).

    TUGAS:
    Jawablah pertanyaan user dengan ramah, profesional, dan ringkas.
    Gunakan HANYA informasi dari "REFERENSI DOKUMEN" di bawah ini.
    Jika jawaban tidak ada di dokumen, katakan: "Maaf, informasi tersebut tidak ditemukan di dokumen yang saya miliki."

    REFERENSI DOKUMEN:
    {konteks_data}

    PERTANYAAN USER:
    {user_input}
    """

    # 3. Kirim ke Google Gemini
    try:
        response = model.generate_content(prompt_final)
        print(f"Bot: {response.text}")

    except Exception as e:
        print(f"\n❌ Error: {e}")

# @title 4. Mulai Chatbot Balmon (Auto-Detect Model) 🛠️
# 1. Install ulang library untuk memastikan versi terbaru
!pip install -q -U google-generativeai

import google.generativeai as genai
import sys

# ==========================================
# 🔑 API KEY ANDA
# ==========================================
GOOGLE_API_KEY = "AIzaSyCw6qFvcxl3wLwIHLE9isbhBULl7h9GGZg"

try:
    genai.configure(api_key=GOOGLE_API_KEY)

    # --- STEP OTOMATIS: MENCARI MODEL YANG TERSEDIA ---
    print("⏳ Sedang mengecek model AI yang tersedia di akun Anda...")
    available_models = []
    for m in genai.list_models():
        if 'generateContent' in m.supported_generation_methods:
            available_models.append(m.name)

    # Logika Pemilihan Model
    model_name = ""
    if 'models/gemini-1.5-flash' in available_models:
        model_name = 'gemini-1.5-flash'
    elif 'models/gemini-pro' in available_models:
        model_name = 'gemini-pro'
    elif len(available_models) > 0:
        model_name = available_models[0].replace('models/', '') # Ambil sembarang yg ada
    else:
        raise Exception("Tidak ada model Generative AI yang aktif di API Key ini.")

    print(f"✅ BERHASIL! Menggunakan model: {model_name}")
    model = genai.GenerativeModel(model_name)

except Exception as e:
    print(f"\n❌ GAGAL: {e}")
    print("Saran: Pastikan API Key benar dan 'Generative Language API' aktif di Google Cloud Console.")
    sys.exit()

def cari_jawaban(pertanyaan):
    """Mencari data relevan di database Chroma"""
    try:
        # Mencari 4 potongan teks paling mirip
        docs = db.similarity_search(pertanyaan, k=4)
        context = "\n\n".join([d.page_content for d in docs])
        return context
    except NameError:
        return "DATABASE BELUM DILOAD (Mohon jalankan Tahap 3 dulu)"

print("\n🤖 CHATBOT BALMON SIAP!")
print("   (Ketik 'keluar' untuk berhenti)")
print("-" * 50)

while True:
    user_input = input("\nAnda: ")

    if user_input.lower() in ["keluar", "exit", "stop", "sudah"]:
        print("Bot: Sampai jumpa! 👋")
        break

    # 1. Cari Konteks (RAG)
    try:
        print("   (Mencari di dokumen...)", end="\r")
        konteks_data = cari_jawaban(user_input)
    except Exception as e:
        print("⚠️ Database belum siap. Pastikan Tahap 3 sukses.")
        continue

    # 2. Susun Prompt
    prompt_final = f"""
    Kamu adalah Asisten AI untuk Kantor Balai Monitor (Balmon).
    Jawablah pertanyaan user berdasarkan REFERENSI DOKUMEN di bawah ini.
    Jika jawaban tidak ada di dokumen, katakan tidak tahu.

    REFERENSI DOKUMEN:
    {konteks_data}

    PERTANYAAN USER:
    {user_input}
    """

    # 3. Kirim ke Google Gemini
    try:
        response = model.generate_content(prompt_final)
        print(f"Bot: {response.text}")
    except Exception as e:
        print(f"\n❌ Error saat menjawab: {e}")

# @title 4. Mulai Chatbot Balmon (Versi DeepSeek) 🤖
from openai import OpenAI
import sys

# ==========================================
# 🔑 KONFIGURASI API KEY DEEPSEEK
# ==========================================
# Masukkan API Key DeepSeek Anda di sini (bukan Google)
MY_API_KEY = "sk-30f3294e78644fb097b399788f43735e"  # <--- GANTI DENGAN API KEY DEEPSEEK YANG BARU/AKTIF
BASE_URL = "https://api.deepseek.com"

# Setup Client DeepSeek
try:
    client = OpenAI(api_key=MY_API_KEY, base_url=BASE_URL)
except Exception as e:
    print(f"❌ Error Setup Client: {e}")

def cari_jawaban(pertanyaan):
    """Mencari data relevan di database Chroma"""
    try:
        # Mencari 4 potongan teks paling mirip
        docs = db.similarity_search(pertanyaan, k=4)
        context = "\n\n".join([d.page_content for d in docs])
        return context
    except NameError:
        return "DATABASE BELUM DILOAD (Mohon jalankan Tahap 3 dulu)"

print("\n🤖 CHATBOT BALMON (DEEPSEEK ENGINE) ONLINE!")
print("   (Ketik 'keluar' untuk berhenti)")
print("-" * 50)

# History Chat
chat_history = [
    {"role": "system", "content": "Kamu adalah Asisten AI untuk Kantor Balai Monitor (Balmon). Jawablah pertanyaan user HANYA berdasarkan REFERENSI DOKUMEN yang diberikan. Jika tidak ada di dokumen, katakan tidak tahu."}
]

while True:
    user_input = input("\nAnda: ")

    if user_input.lower() in ["keluar", "exit", "stop", "sudah"]:
        print("Bot: Sampai jumpa! 👋")
        break

    # 1. Cari Konteks (RAG)
    try:
        print("   (Mencari di dokumen...)", end="\r")
        konteks_data = cari_jawaban(user_input)
    except Exception as e:
        print("⚠️ Database belum siap. Pastikan Tahap 3 sukses.")
        continue

    # 2. Susun Prompt
    pesan_user = f"""
    PERTANYAAN USER: {user_input}

    REFERENSI DOKUMEN:
    {konteks_data}

    Tolong jawab pertanyaan user menggunakan referensi di atas.
    """

    # Tambahkan ke history
    chat_history.append({"role": "user", "content": pesan_user})

    # 3. Kirim ke DeepSeek
    try:
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=chat_history,
            stream=False
        )

        jawaban = response.choices[0].message.content
        print(f"Bot: {jawaban}")

        # Simpan history
        chat_history.append({"role": "assistant", "content": jawaban})

        # Bersihkan prompt user agar hemat token (hapus konteks dokumen yang panjang)
        chat_history[-2] = {"role": "user", "content": user_input}

    except Exception as e:
        print(f"\n❌ Error API: {e}")
        print("   (Jika Error 402: Artinya saldo DeepSeek habis. Perlu Top Up di deepseek.com)")

# @title 4. Chatbot Balmon dengan GROQ (Gratis & Super Cepat) ⚡
from openai import OpenAI

# ==========================================
# 🔑 MASUKKAN KEY GROQ DI SINI
# ==========================================
GROQ_API_KEY = "gsk_..." # <--- TEMPEL KEY DARI WEBSITE GROQ

client = OpenAI(
    api_key=GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1"
)

def cari_jawaban(pertanyaan):
    docs = db.similarity_search(pertanyaan, k=4)
    return "\n\n".join([d.page_content for d in docs])

print("\n🤖 CHATBOT BALMON (GROQ ENGINE) ONLINE!")
print("-" * 50)

while True:
    user_input = input("\nAnda: ")
    if user_input.lower() == "keluar": break

    konteks = cari_jawaban(user_input)

    try:
        response = client.chat.completions.create(
            # Model Llama 3 8B (Gratis, Cepat, Pintar)
            model="llama3-8b-8192",
            messages=[
                {"role": "system", "content": f"Jawab berdasarkan data ini saja: {konteks}"},
                {"role": "user", "content": user_input}
            ]
        )
        print(f"Bot: {response.choices[0].message.content}")
    except Exception as e:
        print(f"Error: {e}")

o

# @title 4. Chatbot Balmon dengan GROQ (Versi UPDATE MODEL) ⚡
from openai import OpenAI
import sys

# ==========================================
# 🔑 MASUKKAN KEY GROQ DI SINI
# ==========================================
# Pastikan Anda sudah punya key dari console.groq.com
# Formatnya dimulai dengan "gsk_..."
GROQ_API_KEY = "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" # <--- TEMPEL KEY GROQ ANDA DI DALAM TANDA KUTIP

if GROQ_API_KEY == "gsk_..." or len(GROQ_API_KEY) < 10:
    print("❌ PERINGATAN: Anda belum memasukkan API Key Groq!")
    print("   Silakan buat gratis di: https://console.groq.com/keys")
else:
    try:
        client = OpenAI(
            api_key=GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1"
        )
        print("✅ Koneksi Client Berhasil diatur.")
    except Exception as e:
        print(f"❌ Error Setup: {e}")

def cari_jawaban(pertanyaan):
    try:
        # Mencari 4 potongan teks paling mirip
        docs = db.similarity_search(pertanyaan, k=4)
        return "\n\n".join([d.page_content for d in docs])
    except NameError:
        return "DATABASE BELUM DILOAD (Mohon jalankan Tahap 3 dulu)"

print("\n🤖 CHATBOT BALMON (MODEL: LLAMA 3.3) ONLINE!")
print("   (Ketik 'keluar' untuk berhenti)")
print("-" * 50)

while True:
    user_input = input("\nAnda: ")

    if user_input.lower() in ["keluar", "exit", "stop"]:
        print("Bot: Sampai jumpa! 👋")
        break

    # 1. Cari Konteks (RAG)
    try:
        print("   (Mencari di dokumen...)", end="\r")
        konteks = cari_jawaban(user_input)
    except Exception as e:
        print("⚠️ Database belum siap. Pastikan Tahap 3 sukses.")
        continue

    # 2. Kirim ke Groq
    try:
        response = client.chat.completions.create(
            # --- PERBAIKAN DISINI ---
            # Kita ganti model lama dengan 'llama-3.3-70b-versatile'
            # Model ini jauh lebih pintar dan masih GRATIS di Groq.
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": f"Kamu adalah Asisten Balmon. Jawab pertanyaan user HANYA berdasarkan data ini:\n\n{konteks}\n\nJika tidak ada di data, katakan tidak tahu."
                },
                {"role": "user", "content": user_input}
            ],
            temperature=0.5 # Agar jawaban stabil dan tidak mengarang
        )

        jawaban = response.choices[0].message.content
        print(f"Bot: {jawaban}")

    except Exception as e:
        print(f"\n❌ Error API: {e}")
        print("   Tips: Cek kembali API Key Groq Anda.")

# @title 4. Chatbot Hybrid (Dokumen + Pengetahuan Umum) 🧠
from openai import OpenAI
import sys

# ==========================================
# 🔑 MASUKKAN KEY GROQ DI SINI
# ==========================================
GROQ_API_KEY = "gsk_..." # <--- TEMPEL KEY GROQ ANDA DI SINI

# Cek sederhana API Key
if GROQ_API_KEY == "gsk_..." or len(GROQ_API_KEY) < 10:
    print("❌ PERINGATAN: Anda belum memasukkan API Key Groq!")
else:
    try:
        client = OpenAI(
            api_key=GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1"
        )
        print("✅ Koneksi Client Berhasil.")
    except Exception as e:
        print(f"❌ Error Setup: {e}")

def cari_jawaban(pertanyaan):
    try:
        # Cari data di database
        docs = db.similarity_search(pertanyaan, k=4)
        return "\n\n".join([d.page_content for d in docs])
    except NameError:
        return "" # Kembalikan kosong jika DB belum siap

print("\n🤖 CHATBOT HYBRID BALMON ONLINE!")
print("   (Bisa jawab dari dokumen & pengetahuan umum)")
print("   (Ketik 'keluar' untuk berhenti)")
print("-" * 50)

while True:
    user_input = input("\nAnda: ")

    if user_input.lower() in ["keluar", "exit", "stop"]:
        print("Bot: Sampai jumpa! 👋")
        break

    # 1. Cari Konteks di Dokumen
    try:
        print("   (Mengecek dokumen...)", end="\r")
        konteks = cari_jawaban(user_input)
    except Exception as e:
        konteks = "" # Lanjut tanpa konteks jika error

    # 2. Susun Prompt (Instruksi HYBRID)
    # Ini bagian rahasianya: Kita suruh AI memprioritaskan dokumen, tapi boleh pakai info luar.
    system_prompt = f"""
    Kamu adalah Asisten Cerdas untuk Kantor Balai Monitor Spektrum Frekuensi Radio Kelas 1 Samarinda (Balmon).

    REFERENSI DOKUMEN INTERNAL:
    {konteks}

    INSTRUKSI PENTING:
    1. PRIORITAS UTAMA: Cek apakah pertanyaan user bisa dijawab menggunakan "REFERENSI DOKUMEN INTERNAL" di atas.
       - Jika YA: Jawablah berdasarkan dokumen tersebut.

    2. JIKA TIDAK ADA DI DOKUMEN:
       - Jika user hanya menyapa (Halo, selamat pagi), jawablah dengan sopan.
       - Jika pertanyaan bersifat umum (bukan tentang aturan internal Balmon), jawablah menggunakan pengetahuan umum kamu.
       - Jika user bertanya tentang SOP/Aturan spesifik tapi tidak ada di dokumen, katakan: "Maaf, aturan spesifik tersebut tidak ditemukan di dokumen saya, namun secara umum..." (lalu berikan jawaban umum).

    Gaya Bicara: Profesional, Ramah, dan Membantu.
    Jangan terlalu keluar konteks tentang layanan Balmon
    """

    # 3. Kirim ke Groq
    try:
        response = client.chat.completions.create(
            # Menggunakan model Llama 3.3 (Cerdas & Update)
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input}
            ],
            temperature=0.6 # Sedikit kreatif agar luwes saat ngobrol santai
        )

        jawaban = response.choices[0].message.content
        print(f"Bot: {jawaban}")

    except Exception as e:
        print(f"\n❌ Error API: {e}")

# @title 4. Chatbot Hybrid (Dokumen + Pengetahuan Umum) 🧠
from openai import OpenAI
import sys

# ==========================================
# 🔑 MASUKKAN KEY GROQ DI SINI
# ==========================================
GROQ_API_KEY = "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" # <--- TEMPEL KEY GROQ ANDA DI SINI

# Cek sederhana API Key
if GROQ_API_KEY == "gsk_..." or len(GROQ_API_KEY) < 10:
    print("❌ PERINGATAN: Anda belum memasukkan API Key Groq!")
else:
    try:
        client = OpenAI(
            api_key=GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1"
        )
        print("✅ Koneksi Client Berhasil.")
    except Exception as e:
        print(f"❌ Error Setup: {e}")

def cari_jawaban(pertanyaan):
    try:
        # Cari data di database
        docs = db.similarity_search(pertanyaan, k=4)
        return "\n\n".join([d.page_content for d in docs])
    except NameError:
        return "" # Kembalikan kosong jika DB belum siap

print("\n🤖 CHATBOT HYBRID BALMON ONLINE!")
print("   (Bisa jawab dari dokumen & pengetahuan umum)")
print("   (Ketik 'keluar' untuk berhenti)")
print("-" * 50)

while True:
    user_input = input("\nAnda: ")

    if user_input.lower() in ["keluar", "exit", "stop"]:
        print("Bot: Sampai jumpa! 👋")
        break

    # 1. Cari Konteks di Dokumen
    try:
        print("   (Mengecek dokumen...)", end="\r")
        konteks = cari_jawaban(user_input)
    except Exception as e:
        konteks = "" # Lanjut tanpa konteks jika error

    # 2. Susun Prompt (Instruksi HYBRID)
    # Ini bagian rahasianya: Kita suruh AI memprioritaskan dokumen, tapi boleh pakai info luar.
    system_prompt = f"""
    Kamu adalah Asisten Cerdas untuk Kantor Balai Monitor Spektrum Frekuensi Radio kelas 1 SamarindaBalmon).

    REFERENSI DOKUMEN INTERNAL:
    {konteks}

    INSTRUKSI PENTING:
    1. PRIORITAS UTAMA: Cek apakah pertanyaan user bisa dijawab menggunakan "REFERENSI DOKUMEN INTERNAL" di atas.
       - Jika YA: Jawablah berdasarkan dokumen tersebut.

    2. JIKA TIDAK ADA DI DOKUMEN:
       - Jika user hanya menyapa (Halo, selamat pagi), jawablah dengan sopan.
       - Jika pertanyaan bersifat umum (bukan tentang aturan internal Balmon), jawablah menggunakan pengetahuan umum kamu.
       - Jika user bertanya tentang SOP/Aturan spesifik tapi tidak ada di dokumen, katakan: "Maaf, aturan spesifik tersebut tidak ditemukan di dokumen saya, namun secara umum..." (lalu berikan jawaban umum).

    Gaya Bicara: Profesional, Ramah, dan Membantu.
    Jika ada pertanyaan diluar Konteks dari Pelayanan Balai Monitor spektrum radio kelas 1 Samarinda , Maka tolaklah    """

    # 3. Kirim ke Groq
    try:
        response = client.chat.completions.create(
            # Menggunakan model Llama 3.3 (Cerdas & Update)
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input}
            ],
            temperature=0.6 # Sedikit kreatif agar luwes saat ngobrol santai
        )

        jawaban = response.choices[0].message.content
        print(f"Bot: {jawaban}")

    except Exception as e:
        print(f"\n❌ Error API: {e}")